service: ${self:custom.prefix}-backend

provider:
  name: aws
  runtime: python3.11
  region: ${opt:region}
  stage: ${opt:stage}
  stackName: ${self:custom.prefix}-backend
  iam:
    role:
      name: ${self:custom.prefix}-backend-role
      statements:
        - Effect: 'Allow'
          Action: '*'
          Resource: '*'
  deploymentBucket:
    name: ${self:custom.prefix}-deployments
  environment:
    REGION: ${opt:region}
    STAGE: ${opt:stage}
    DOMAIN: ".gm.perfect-projects.link"

package:
  excludeDevDependencies: true
  individually: true
  patterns:
    - '!node_modules/**'
    - '!data-storage/**'
    - '!access/**'
    - '!cert/**'

custom:
  prefix: grind-meter-${self:provider.stage}-${self:provider.region}
  customCertificate:
    certificateName: api.gm.perfect-projects.link
    hostedZoneIds: Z0244622OB5I5GBJSX1D
    region: us-east-1 # This specific region is required due to an error from Serverless Domain Manager
  customDomain:
    domainName: api.gm.perfect-projects.link
    certificateName: api.gm.perfect-projects.link
    createRoute53Record: true
    endpointType: edge
    securityPolicy: tls_1_2
    apiType: rest

functions:
  api:
    handler: backend.app.main.handler
    environment:
      STAGE: ${self:provider.stage}
    events:
      - http:
          method: any
          path: /{proxy+}

plugins:
  - serverless-deployment-bucket
  - serverless-python-requirements
  - serverless-certificate-creator
  - serverless-domain-manager