service: ${self:custom.prefix}-data-storage

frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.9
  lambdaHashingVersion: 20201221
  region: ${opt:region}
  stage: ${opt:stage}
  stackName: ${self:custom.prefix}-data-storage
  iam:
    role:
      name: ${self:custom.prefix}-data-storage-role
      statements:
        - Effect: 'Allow'
          Resource: '*'
          Action: 'iam:DeleteBucket'
  deploymentBucket:
    name: ${self:custom.prefix}-deployments

plugins:
  - serverless-deployment-bucket

custom:
  prefix: grind-meter-${self:provider.stage}

resources:
    Resources:
        grindMeterStorage:
          Type: AWS::S3::Bucket
          Properties:
            AccessControl: Private
            BucketName: ${self:custom.prefix}-storage
        userExercise:
            Type: AWS::DynamoDB::Table
            Properties:
                TableName: ${self:custom.prefix}-user-exercise
                AttributeDefinitions:
                    - AttributeName: user_id
                      AttributeType: S
                    - AttributeName: exercise_id
                      AttributeType: S
                KeySchema:
                  - AttributeName: user_id
                    KeyType: HASH
                  - AttributeName: exercise_id
                    KeyType: RANGE
                GlobalSecondaryIndexes:
                  - IndexName: user_id
                    KeySchema:
                      - AttributeName: user_id
                        KeyType: HASH
                    Projection:
                      ProjectionType: "ALL"
                BillingMode: PAY_PER_REQUEST
        userExerciseReport:
          Type: AWS::DynamoDB::Table
          Properties:
            TableName: ${self:custom.prefix}-user-exercise-report
            AttributeDefinitions:
              - AttributeName: exercise_id-user_id
                AttributeType: S
              - AttributeName: day_timestamp
                AttributeType: S
            KeySchema:
              - AttributeName: exercise_id-user_id
                KeyType: HASH
              - AttributeName: day_timestamp
                KeyType: RANGE
            BillingMode: PAY_PER_REQUEST