service: ${self:custom.prefix}-data-storage

frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.11
  lambdaHashingVersion: 20201221
  region: ${opt:region}
  stage: ${opt:stage}
  stackName: ${self:custom.prefix}-data-storage
  iam:
    role:
      name: ${self:custom.prefix}-data-storage-role
      statements:
        - Effect: 'Allow'
          Resource: '*'
          Action: 'iam:DeleteBucket'
  deploymentBucket:
    name: ${self:custom.prefix}-deployments

plugins:
  - serverless-deployment-bucket

custom:
  prefix: grind-meter-${self:provider.stage}-${self:provider.region}

resources:
    Resources:
        grindMeterStorage:
          Type: AWS::S3::Bucket
          Properties:
            AccessControl: Private
            BucketName: ${self:custom.prefix}-exercises
        grindMeterProjectTable:
            Type: AWS::DynamoDB::Table
            Properties:
                TableName: ${self:custom.prefix}-projects
                AttributeDefinitions:
                    - AttributeName: id
                      AttributeType: S
                    - AttributeName: name
                      AttributeType: S
                KeySchema:
                  - AttributeName: id
                    KeyType: HASH
                  - AttributeName: name
                    KeyType: RANGE
                BillingMode: PAY_PER_REQUEST